apiVersion: v1
kind: Service
metadata:
  name: netflix-app-service
  labels:
    app: netflix-app
spec:
  selector:
    app: netflix-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  
  type: ClusterIP  # Change from NodePort to ClusterIP
