apiVersion: v1
kind: Service
metadata:
  name: netflix-app-service
  labels:
    app: netflix-app
spec:
  selector:
    app: netflix-app
  ports:
    - protocol: TCP
      port: 80        # Service port (external)
      targetPort: 80  # Change this from 3000 to 80
      nodePort: 30080 # Fixed NodePort
  type: NodePort
