apiVersion: v1
kind: Service
metadata:
  name: netflix-app-service
  labels:
    app: netflix-app
spec:
  selector:
    app: netflix-app  # This must match your Deployment labels
  ports:
    - protocol: TCP
      port: 80        # Service port (external)
      targetPort: 8080 # Container port (internal)
  type: NodePort
  ports:
    - port: 80
    targetPort: 8080
    nodePort: 30080  # Optional: K8s will assign if not specified
